version: '3.4'

services:
  mastersanta2024:
    image: mastersanta2024
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
